name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   

    - name: Login to ECR
      run:  aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k5c6v6o7

    - name: Build Docker image
      run: docker build -t youtube:latest . 
    
    - name: Tag Image       
      run: docker tag youtube:latest public.ecr.aws/k5c6v6o7/youtube:latest

    - name: Push Docker image to Docker Hub
      run: docker push public.ecr.aws/k5c6v6o7/youtube:latest

    - name: Update ECS service
      run: |
            aws ecs update-service --cluster mycluster --service node-service --force-new-deployment --region us-east-1
